delete from lineaspedidos where idlineapedido>0;
delete from ejemplares where idejemplar>0;
delete from pedidos where idpedido>0;
delete from productos where idproducto>0;
delete from plataformas where idplataforma>0;
delete from usuarios where idusuario>0;
delete from roles where idrole>0;

ALTER TABLE lineaspedidos AUTO_INCREMENT = 1;
ALTER TABLE ejemplares AUTO_INCREMENT = 1;
ALTER TABLE pedidos AUTO_INCREMENT = 1;
ALTER TABLE plataformas AUTO_INCREMENT = 1;
ALTER TABLE productos AUTO_INCREMENT = 1;
ALTER TABLE usuarios AUTO_INCREMENT = 1;
ALTER TABLE roles AUTO_INCREMENT = 1;

insert into plataformas (nombre, imagen) values ('Steam', 'imagenSteam.jpg');
insert into plataformas (nombre, imagen) values ('Switch', 'imagenNintendoSwitch.png');
insert into plataformas (nombre, imagen) values ('Xbox One', 'imagenXboxOne.webp');
insert into plataformas (nombre, imagen) values ('PS5', 'imagenPS5.jpg');
insert into plataformas (nombre, imagen) values ('Epic Games', 'imagenEpicGames.webp');
insert into plataformas (nombre, imagen) values ('Battle.net', 'imagenBattlenet.png');

insert into roles (nombre) values ('ADMIN');
insert into roles (nombre) values ('USER');

insert into productos (imagen, fechasalida, nombre, precio, descuento, idplataforma, resumen, sinopsis) values
('EldenRing.jpg' ,'2022-02-25', 'Elden Ring', 45.99, 10, 1, 'Elden Ring para PC es un RPG de acción (ARPG) escrito por las superestrellas George RR Martin 
(el autor de la serie de libros Song of Ice and Fire que engendró la serie de televisión Game of Thrones) y Hidetaka Miyazaki (que es famoso por muchos videojuegos, 
como los de la serie Souls, Bloodborne o Sekiro, entre otros).', 'El Círculo de Elden ha sido destruido y sus fragmentos se han esparcido por las tierras, formando las Grandes Runas. 
Algunos de estos fragmentos han caído en manos de los hijos de la reina Márika la Eterna, y la promesa de aún más poder ha corrompido a cada uno de los seis semidioses.
Las personas que viven en la tierra, solían disfrutar de la Gracia del Círculo, otorgada por el Erdtree, que se mostraba con una especie de brillo dorado en los ojos: este brillo se ha desvanecido, 
lo que indica la pérdida de la Gracia, y los que quedan son ahora llamados "Sinluz". Eres uno de ellos, un exiliado de las Tierras Intermedias, debido a la pérdida de Gracia, 
y ahora es tu trabajo encontrar los fragmentos, restaurar el Círculo y convertirte en el Señor del Círculo, regresando el bien a la tierra.'),
('DarkSoulsRemastered.jpg' ,'2018-05-24', 'DarkSouls Remastered', 19.99, 50, 4, 'Actualmente, estamos en proceso de restaurar los servidores online para la serie Dark Souls en PC.
Nuestro plan es restablecer el servicio online para cada juego de forma progresiva y recuperar los servidores de DARK SOULS: REMASTERED una vez hayamos completado el trabajo necesario para corregir el problema. Ofreceremos actualizaciones adicionales en cuanto completemos nuestra planificación.
Queremos daros las gracias a todos los jugadores por vuestra paciencia y comprensión mientras solucionamos este problema.','Entonces llegó el Fuego. Vuelve a disfrutar del aclamado juego que definió el género con el que empezó todo. Gracias a una magnífica remasterización, podrás regresar a Lordran con unos impresionantes detalles en alta definición y a 60 fps.
Dark Souls Remastered incluye el juego principal y el contenido descargable "Artorias of the Abyss".'),
('DarkSouls3.jpg' ,'2016-03-24', 'DarkSouls 3', 29.99, 20, 3,'Dark Souls 3 para PC es un RPG de acción y fantasía, el cuarto de la serie y una secuela directa de Dark Souls 2, su predecesor inmediato. El juego se desarrolla en un universo ficticio, en el Reino de Lothric, donde un largo período de iluminación está siendo amenazado por la llegada de la Edad Oscura.
El jugador debe luchar por la supervivencia de la Edad de Fuego, asegurando que la Primera Llama siga ardiendo durante más tiempo.','El jugador asume el control en tercera persona de un personaje llamado Ser de la Ceniza, a quien se le encomienda la tarea de ‘enlazar’ a la Primera Llama para que siga encendida. La llama se alimenta de los sacrificios de héroes y campeones, quienes sacrifican sus almas por la llama voluntariamente, convirtiéndose así en Señores de la Ceniza. Esto ha ocurrido de manera ininterrumpida desde tiempos inmemoriales, hasta ahora. El Ser de la Cenizo no logró enlazar la llama y por ende no se ha convertido en un Señor de la Ceniza, siendo en cambio conocido como un Latente.'),
('EldenRing.jpg' ,'2022-02-25', 'Elden Ring', 45.99, 15, 3,'Elden Ring para PC es un RPG de acción (ARPG) escrito por las superestrellas George RR Martin 
(el autor de la serie de libros Song of Ice and Fire que engendró la serie de televisión Game of Thrones) y Hidetaka Miyazaki (que es famoso por muchos videojuegos, 
como los de la serie Souls, Bloodborne o Sekiro, entre otros).', 'El Círculo de Elden ha sido destruido y sus fragmentos se han esparcido por las tierras, formando las Grandes Runas. 
Algunos de estos fragmentos han caído en manos de los hijos de la reina Márika la Eterna, y la promesa de aún más poder ha corrompido a cada uno de los seis semidioses.
Las personas que viven en la tierra, solían disfrutar de la Gracia del Círculo, otorgada por el Erdtree, que se mostraba con una especie de brillo dorado en los ojos: este brillo se ha desvanecido, 
lo que indica la pérdida de la Gracia, y los que quedan son ahora llamados "Sinluz". Eres uno de ellos, un exiliado de las Tierras Intermedias, debido a la pérdida de Gracia, 
y ahora es tu trabajo encontrar los fragmentos, restaurar el Círculo y convertirte en el Señor del Círculo, regresando el bien a la tierra.'),
('TheElderScrollsOnline.jpg' ,'2014-04-04', 'The Elder Scrolls Online', 15.99, 20, 1,'The Elder Scrolls Online para PC es un juego de rol en línea del género multijugador masivo (MMORPG) que forma parte de la serie Elder Scrolls y es la primera oferta multijugador del juego. Situado en el continente ficticio de Tamriel, como todos los demás juegos de la serie, el juego no está directamente relacionado con ninguno de los otros. Se trata de una entrega independiente en un mundo familiar para los jugadores asiduos de la serie, pero aún así accesible para los recién llegados.
Más de diez millones de personas han jugado el juego desde su lanzamiento inicial, y alrededor de un millón de personas al mes se registran para disfrutar del juego en cualquier momento.','La jugabilidad es no-lineal, ya que los jugadores pueden elegir sus misiones de entre una gran variedad de opciones. Puedes vagar libremente por el mundo, disfrutando de un estilo de juego ‘sandbox’ y desentrañando los secretos de Tamriel. La decisión de llevar a cabo las misiones es completamente tuya, y puedes no hacerlas si así lo prefieres. O bien, puedes aceptar todas las misiones que se te ofrezcan y permanecer atento a los eventos aleatorios, aprovechando la oportunidad de ganar premios para llegar a lo más alto de la tabla de clasificación.
Hay dos conflictos simultáneos en curso: una batalla por el Trono Imperial, la cual otorgará el poder sobre todo Tamriel al ganador, y una lucha contra el Príncipe Molag Bal, un Daedra, quien debe ser detenido antes de que complete su misión.
El jugador puede tomarse el tiempo que desee antes de comenzar completar estas tareas, explorando el mundo abierto a sus anchas e ignorando estos dos llamados a la acción hasta que se sienta listo para abordarlos.'),
('CoreKeeper.jpg' ,'2022-01-01', 'Core Keeper', 29.99, 30, 1,'Atraído hacia una reliquia misteriosa, eres un explorador que despierta en una antigua caverna de criaturas, recursos y abalorios. Atrapado en las profundidades subterráneas, ¿estarán a la altura tus habilidades de supervivencia?
Extrae reliquias y recursos para construir tu base, fabricar nuevos utensilios, sobrevivir y alimentar el Núcleo. Vence a monstruos gigantes, descubre secretos ocultos, cultiva, cocina nuevas recetas y explora un mundo subterráneo generado de manera procedimental en una aventura de minería tipo «sandbox» para 1-8 jugadores.','Explora una inmensa cueva subterránea de recursos infinitos. Extrae minerales, descubre cristales ocultos, fósiles y abalorios y sobrevive en un mundo subterráneo generado de manera procedimental. Explora biomas vivos y lucha con criaturas cavernícolas en un gran sistema subterráneo. Peina el oscuro mundo que te rodea y enfréntate a los mastodontes del inframundo. Derrótalos y recoge el botín para ayudarte a desvelar el misterio del Núcleo. Personaliza a tu personaje y fabrica nuevos objetos, armaduras y utensilios para adentrarte más en las cuevas. Fabrica un pico para explotar paredes y recursos, construye puentes para cruzar lagos subterráneos y coloca antorchas para iluminar la profunda y omnipresente oscuridad. Cultiva distintas plantas sembrando semillas que encontrarás en tus aventuras. Busca el sitio perfecto para pescar y captura una plétora de peces únicos. Combina en la olla el producto de tu duro trabajo cultivando y pescando para descubrir deliciosas recetas con efectos inesperados. Sobrevive en solitario o juega en línea con hasta 7 jugadores más. Colabora con ellos para extraer recursos, luchar, cultivar, fabricar y sobrevivir juntos. Especialízate en tu papel para ayudar a otros exploradores a dominar el díscolo paisaje en el que os encontráis.'),
('FallGuys.jpg', '2020-08-04', 'FallGuys', 9.99, 70, 5, 'Fall Guys: Ultimate Knockout para PC es otro juego battle royale, que aprovecha la popularidad interminable de este formato, pero en una versión divertida y peculiar del género. Eres un muñeco con forma de gelatina con cara y extremidades, y competirás contra otros sesenta aspirantes a ser el último en pie después de una serie de cuatro a seis juegos divertidos.', 'Participa en una serie de divertidos juegos contra otros 59 jugadores online, con el objetivo de llegar a la última etapa, momento en el que hay una batalla a muerte, dejando solo un vencedor. Pero este juego no es un "el ganador se lo lleva todo", con recompensas otorgadas en cada una de las distintas etapas.
Las recompensas toman la forma de moneda del juego, con skins y más, para que puedas cambiar tu cuerpo de gelatina y convertirlo en algo único y divertido: ¿una cabeza de piña con un tutú rosa? ¡Hecho! Las monedas te las dan por hacerlo bien, terminando entre los cinco primeros, o sino te dan "coronas", que se ganan por llegar primero en los niveles a medida que se avanza.'),
('MarioStrikersBLF.jpg' ,'2022-06-10', 'Mario Strikers: BLF', 69.99, 10, 2,'¡Pasa el balón, haz entradas, usa objetos capaces de cambiar el curso del partido y marca con hipertrallazos para llevarte la victoria en Mario Strikers: Battle League Football para Nintendo Switch! Haz todo lo que esté en tu mano para ganar en el caótico modo multijugador local, y aúna fuerzas con otros jugadores en línea para llevar tu club a lo más alto de la clasificación.','Mario y sus amigos se ven las caras en el strike, un deporte de cinco contra cinco similar al fútbol, ¡pero sin ninguna de sus molestas reglas!
Gana el equipo que marque más goles, pero con las devastadoras entradas en equipo y toda suerte de objetos, sin olvidar las vallas eléctrificadas que delimitan el campo de juego, ¡marcar goles no resultará tan sencillo como podría parecer!
Eso sí, si logras meter el balón en la portería con un hipertrallazo, ¡contará como dos tantos! Qué alucine...'),
('NintendoSwitchSports.webp' ,'2022-04-29', 'Nintendo Switch Sports', 29.99, 10, 2,'Levántate y juega
¡Logra la victoria con raquetazos, chutes y remates en Nintendo Switch Sports para Nintendo Switch!','Los movimientos que hagas con el mando Joy-Con se reproducirán dentro del juego mientras disfrutas de una variedad de actividades deportivas que te pondrán en marcha. Reúne a tu familia y amigos para pasártelo en grande con ellos en la misma consola Nintendo Switch, o busca a nuevos rivales con el modo multijugador en línea.
Si te gusta darle patadas a un balón, el fútbol es ideal para ti. Tampoco te pierdas las pistas de tenis, bádminton y voleibol, anímate a disputar partidas de bolos o pon a prueba tus dotes con la espada jugando a chambara.'),
('Hearthstone5Sobres.jpg', '2014-03-11', 'Hearthstone - 5 Sobres', 5.99, 10, 6, '¡Atención! En una misma cuenta puedes canjear un máximo de 15 códigos.', 'Este código añadirá 5 Booster Packs a tu cuenta que te proporcionarán 5 cartas expertas al azar, con la garantía de recibir al menos una carta rara.'),
('TemTem.jpg', '2020-01-21', 'TemTem', 29.99, 30, 1, 'Temtem para PC es un videojuego de rol multijugador masivo en línea o MMORPG inspirado en Pokémon en el que el jugador aspira a coleccionar criaturas, al igual que los jugadores de Pokémon aspiran a tener cuantos más Pokémon mejor. Sin embargo, Temtem tiene unas características y una jugabilidad que lo convierten en un título único y convincente por derecho propio.', 'Juega a través de seis islas, cada una con diferentes terrenos y estéticas, que incluyen todo, desde volcanes hasta paraísos tropicales, desde cuevas cubiertas de cristales hasta sabanas bañadas por el sol. (Ver más información sobre esto abajo). Hay doce tipos diferentes de Temtem, todos vinculados a los distintos tipos de terreno, por ejemplo, los Temtem de tipo Melee y Mental se encuentran en la isla de Arbury, que es conocida por ser un lugar de abundante lluvia y exuberantes montañas verdes.
Cada jugador debe explorar la región en la que se encuentra, buscando Temtem salvajes que deben ser cazados, cuidados y entrenados. Estos procesos son interesantes, ya que forman los primeros niveles del juego a medida que el jugador trabaja para llenar su inventario con Temtem salvajes, que a veces resisten los primeros esfuerzos para interactuar y ser capturados.'),
('Sifu.jpg', '2022-02-08', 'Sifu', 39.99, 30, 5, '¿Es una vida suficiente para dominar el kung-fu?
En Sifu, te pondrás en la piel de un joven estudiante de kung-fu que busca venganza.
Mientras huyes de las sombras de tu pasado, tendrás que enfrentarte en solitario a tus rivales y sacar a relucir tu dominio del Pak-Mei kung-fu para sobrevivir.', 'En busca de venganza:
Para dar caza a tus enemigos tendrás que recorrer los rincones ocultos de la ciudad, desde los suburbios repletos de bandas hasta los fríos pasillos de las torres empresariales. Tienes un día y un sinfín de enemigos cortándote el paso. El tiempo será el precio a pagar.
Adaptarse es la clave:
Si quieres sobrevivir, tendrás que posicionarte de manera adecuada y sacar partido del entorno. Usa todo lo que tengas a tu disposición: objetos que se pueden lanzar, armas improvisadas, ventanas, cornisas... Estás en clara desventaja y nadie mostrará piedad ante ti.'),
('RocketLeague.jpg', '2015-07-7', 'Rocket League', 9.99, 70, 5, 'Rocket League para PC es un juego que combina el fútbol con los vehículos, en el que el jugador controla a un automóvil para intentar hacer contacto con una pelota gigante, con el objetivo de anotar goles y alejarla de los contrincantes. Básicamente un partido de fútbol, ¡pero con automóviles propulsados por cohetes en lugar de jugadores! La pelota es más grande que los automóviles, lo que añade un gran atractivo visual a los impactos y a los goles bien logrados.', 'La premisa del juego es de lo más sencilla: dirige tu automóvil propulsado por cohetes hacia la pelota gigante y haz contacto con ella para intentar meterla en la portería. En pocas palabras: ¡marcar goles! Repite la dinámica hasta que la partida termine y – con suerte – ganes. Desde luego, si esto fuera todo, el juego se volvería tedioso demasiado pronto. Pero no tienes nada de qué preocuparte, ya que el juego cuenta con suficientes características adicionales, además de potenciadores e interesantes funciones para que sigas volviendo por más y más horas de conducción intensa y apasionante.'),
('SeaofThieves.jpg', '2018-03-20', 'Sea of Thieves', 49.99, 30, 3, 'Sea of Thieves para PC es un juego de acción y aventuras ambientado en alta mar, en el que los jugadores deben navegar a través de un océano bellamente renderizado. El reflejo de la luz sobre el agua ha sido perfectamente capturado, y el simple hecho de navegar observando el océano es una buena forma de matar el tiempo mientras esperas a que tus amigos se unan a la partida.', 'Los jugadores pueden elegir jugar como piratas o como marineros ordinarios, siempre desde una perspectiva en primera persona. Al jugar como los últimos, se te proporciona una embarcación, un puñado de compañeros (si estás jugando en modo multijugador o cooperativo) y unas cuantas instrucciones del tipo: ‘Navega hacia una isla y trae contigo algún objeto de valor’. Por otro lado, y como es de imaginarse, jugar en el papel de pirata es jugar sin ley, ¡y por ello es potencialmente más divertido! Persigue a otras embarcaciones y atácalas sin cesar para quedarte con su oro y el resto de sus botines, apoderándote de ellas y llevándolas a puerto para conseguir algo de dinero para tu propio beneficio.'),
('Thelastofus.jpg', '2013-06-14', 'The Last of Us', 29.99, 40, 4, 'The Last of Us es un videojuego de terror y de acción y aventura desarrollado por la compañía estadounidense Naughty Dog y distribuido por Sony Computer Entertainment para la consola PlayStation 3 en 2013. La trama describe las vivencias de Joel y Ellie, un par de supervivientes de una pandemia en Estados Unidos que provoca la mutación de los seres humanos en criaturas caníbales.', 'En septiembre de 2013 se desata una pandemia en Estados Unidos ocasionada por una cepa del hongo Cordyceps, que al infectar a los humanos los convierte en criaturas caníbales, y que se transmite a través de una simple mordedura. En medio de la histeria colectiva, Joel (Troy Baker), su hija Sarah (Hana Hayes) y su hermano Tommy (Jeffrey Pierce) abandonan su hogar en los suburbios de Austin, Texas para evitar la infección, pero en el camino son interceptados por un oficial que asesina a Sarah al creer que está infectada.'),
('NoMansSky.jpg', '2016-08-09', "No Man's Sky", 50.59, 50, 3, 'No Man’s Sky para PC es un juego de supervivencia de acción y aventuras, en el que el jugador toma la forma de un humanoide alienígena que aterriza tras estrellarse en un accidente, al que se le suministran los elementos básicos que necesita para sobrevivir, e incluso prosperar.
Equipado con una herramienta multiusos, el jugador puede seguir los consejos en pantalla brindados por una entidad llamada Atlas.', 'Cuando se lanzó al público en 2016, el juego fue aclamado como algo único y maravilloso, aunque los críticos se quejaron debido a que muchas de las funciones prometidas no estaban presentes en la primera versión del juego. Sin embargo, los desarrolladores han cumplido con sus promesas, y características prometidas como la capacidad multijugador, funciones adicionales de construcción, etc., ya están disponibles.
En su mayoría, el juego funciona utilizando algoritmos que ‘crean’ el mundo un tanto antes del progreso del jugador. A esto se le llama generación procedural y es un aspecto positivo del juego, debido a que utiliza menos recursos de los que utilizaría mantener un mundo fijo.
Si los jugadores viajan al mismo lugar al mismo tiempo, verán las mismas características y colonias. Esto hace que la jugabilidad sea más auténtica, manteniendo el uso de datos relativamente bajo.'),
('Overwatch.jpg', '2016-05-24', 'Overwatch', 20.15, 80, 6, 'Overwatch para PC es un shooter multijugador en primera persona basado en equipos. Ha sido Desarrollado por Blizzard Entertainment, también son conocidos por los muy populares juegos de World of Warcraft y sus spin-offs.', 'El juego se desarrolla en un mundo ficticio, sesenta años en el futuro.
La organización de nombre Overwatch era el equivalente a las Naciones Unidas de su tiempo, establecida treinta años antes de la época del juego, pero una serie de disputas y acusaciones tuvieron como resultado una explosión en la sede de la organización, lo que causó la muerte de muchos de los líderes fundadores. Luego de este incidente, seis años antes del comienzo del juego, la organización Overwatch fue disuelta y clausurada, y sus miembros se dispersaron a los cuatro vientos.
En sus inicios, Overwatch se puso en marcha para salvar al mundo de una rebelión de Inteligencia Artificial, cuando los robots diseñados para servir a la humanidad se volvieron contra ella, cuando los llamados programas de Dios tomaron el control y se enfrentaron a sus creadores y amos.
'),
('Sekiro.jpg', '2019-03-21', 'Sekiro', 29.99, 15, 1, 'Sekiro: Shadows Die Twice para PC es un juego de acción y aventuras en tercera persona. El juego se desarrolla en una versión ficticia del Sengoku japonés del siglo XVI. Este fue un período de agitación en Japón, marcado por constantes cambios políticos y continuos conflictos militares, mientras los señores feudales y la nobleza luchaban por expandir sus aspiraciones y fortunas.', 'El propósito de este juego es la aventura, y no tanto la personalización y la acumulación de estadísticas, como sucede con otros videojuegos. Esto significa que no hay mucho que puedas personalizar acerca del personaje, y que tampoco se cuenta con un modo multijugador, todo lo cual permite al jugador enfocarse en la delicadeza y precisión de movimientos necesarias para conseguir la victoria en cada uno de los episodios de combate.

Sin embargo, el juego no carece por completo de estadísticas y personalización. Hay un sistema de habilidades para asegurar que tu personaje alcance el máximo de habilidades necesarias para ganar las sesiones de combate, y también es posible personalizar las habilidades, aunque de una manera bastante moderada - ¡lo suficiente, tal vez, para ofrecerte una ventaja sobre tu oponente!'),
('HaloMCCollection.jpg', '2014-11-11', 'Halo: M.C. Collection', 39.99, 20, 3, 'Por primera vez, la serie que cambió para siempre los juegos en consolas llega a la PC con seis 
exitosos juegos en una sola experiencia épica. Este paquete incluye todos los títulos en la colección que se entregarán con el tiempo, comenzando ahora mismo con Halo: Reach y finalizando con Halo 4 en 2020.'
, 'Comienza tu aventura en Halo hoy mismo al lado del Master Chief en el legendario Halo: Combat Evolved Anniversary. Sigue de cerca la crucial batalla por la humanidad en Halo: Reach, vive la épica saga del 
Master Chief y revela los misterios de un ancestral planeta Halo. Disfruta con las legendarias experiencias multijugador a través de 19 mapas memorables y la capacidad de alternar entre las gráficas 
remasterizadas en la edición de Aniversario y las gráficas originales de la campaña Halo: Combat Evolved.'),
('ZeldaBreathoftheWild.jpg', '2017-03-03', 'Zelda: Breath of the Wild', 49.99, 30, 2, 'The Legend of Zelda: Breath of the Wild para Nintendo Switch es un juego de acción y aventuras de Nintendo, la última entrega de la larga serie de The Legend of Zelda. El juego ofrece un formato de mundo abierto, con amplia libertad y pocas instrucciones para los jugadores. La jugabilidad consiste en recolectar utensilios y materiales, completar misiones secundarias y resolver ingeniosos puzles y mazmorras.', 'Gran parte del encanto de este juego reside en el hecho de que premia la experimentación, por lo que te animamos a que te salgas del guión y explores el inmenso mapa a profundidad. La historia principal del juego puede ser completada de manera no lineal, así que puedes elegir cuándo y cómo completar cada una de las misiones, en lugar de verte obligado a seguir un curso de acción restringido.
Sus espléndidos gráficos, los motores físicos y las actuaciones de voces de primera calidad le han valido el premio al Juego del Año, e incluso ha sido considerado como uno de los mejores videojuegos de todos los tiempos, además de ser como es lógico el juego más vendido de toda la historia de la franquicia de Zelda.'),
('SuperSmashBrosUltimate.jpg', '2018-12-07', 'Super Smash Bros: Ultimate', 39.99, 20, 2, 'Super Smash Bros. Ultimate para Nintendo Switch es un aclamado crossover de lucha que cuenta con una amplia gama de personajes de otros juegos y franquicias, lo cual ha sido posible gracias a la colaboración entre Bandai, Sora y Nintendo. Naturalmente, dado el título del juego, todos los personajes del mundo de la serie de Mario Bros son incluidos, haciendo gala de diferentes habilidades y grados de personalización. Esta es la quinta entrega de la franquicia, y nos ofrece la inmensa cantidad de setenta (¡70!) personajes jugables.', 'La premisa del juego es bastante simple: ¡combatir a tu oponente hasta lograr la victoria! Sin embargo, existen diversos aspectos que hacen que la jugabilidad resulte mucho más interesante, y, por supuesto, ¡divertida! Cada uno de los setenta personajes incluidos cuenta con fortalezas y debilidades únicas; y todos ellos poseen más de un estilo de combate. Como resultado de este extenso repertorio, una inmensa variedad de mecánicas de combate pueden hacerse presentes a lo largo de una misma partida, ¡siendo precisamente esto uno de los mayores atractivos del juego!
Como jugador, lo primero que deberás hacer es elegir a tu personaje una decisión de lo más interesante, sobre todo si no sabes a cuál de los personajes elegirá tu oponente. Una vez iniciada la partida, deberás balancear los distintos estilos de ataque de tu personaje, dependiendo del rival al que te enfrentes. Tu desafío consistirá en adaptar tu estilo de lucha para igualar el combate lo más posible hasta que, finalmente, puedas asestar a tu rival el golpe definitivo.'),
('Diablo3.jpg', '2012-05-15', 'Diablo 3', 13.98, 50, 6, 'Han pasado veinte años desde que los Demonios Mayores fueran derrotados y expulsados del mundo de Santuario. Ahora debes volver al origen de todo, Tristán, para investigar los rumores sobre una estrella caída: la primera señal de la reencarnación del mal, un augurio de que el Final de los Tiempos ha comenzado.
', 'Sacude la tierra, ataca a tus enemigos con fuego y hielo e invoca esbirros de otro mundo gracias a los poderes que te otorga tu heroica condición con una de las muchas clases disponibles.
Aniquila a las hordas infernales y explora las profundidades más oscuras de Santuario en busca de nuevos y poderosos tesoros, incluidos objetos legendarios que cambiarán todo tu estilo de juego y conjuntos de armadura que te proporcionarán bonificaciones dinámicas a medida que vayas descubriendo cada una de sus piezas.'),
('DiabloInmortal.jpg', '2022-06-02', 'Diablo Inmortal', 66.66, 66, 6, 'Mata demonios dondequiera que estés. Un capítulo inédito de la saga Diablo.', 'Lucha contra males ancestrales y desvela la historia de los sucesos transcurridos entre Diablo II y Diablo III en este nuevo RPG de acción multijugador masivo en línea desarrollado para móvil, pero con beta abierta también disponible próximamente en PC. Al arcángel Tyrael se lo da por muerto, y la humanidad está sola para afrontar las consecuencias de sus actos. Los fragmentos de la Piedra del Mundo, aún dotados de un inmenso poder, contaminan la tierra, y los esbirros de Diablo esperan poder controlar ese poder para que el Señor del Terror pueda regresar.'),
("RedDeadRedemption2.jpg", '2018-10-26', "Red Dead Redemption 2", 59.99, 50, 5, 'Red Dead Redemption 2 para PC es un juego de acción y aventuras de mundo abierto en el que el jugador puede vagar libremente. Cuenta algunos elementos en tercera persona, además de otras modalidades de juego en primera persona. El jugador puede cometer crímenes, pero de hacerlo deberá estar preparado para ser perseguido por las fuerzas del orden, ¡quienes estarán dispuestas a hacer valer todo el peso de la ley sobre los delincuentes!', 'RDR2, como se conoce afectuosamente al juego, fue lanzado para otras plataformas antes de ser publicado para PC, y durante el período de su lanzamiento original llegó a posicionarse como uno de los títulos más vendidos de todos los tiempos, incluso antes que se incluyeran las cifras de venta en su versión para PC.
La razón de la popularidad del juego no es difícil de entender. A diferencia de otros juegos en los que el caos y la destrucción son la clave, este juego te permite sumergirte en la belleza de los paisajes del Salvaje Oeste, y formar lazos de empatía y afecto con otros jugadores y con PNJs (personajes no jugables) en los momentos de calma que se te presenten entra una secuencia de acción y otra ¡de las cuales hallarás de sobra!'),
('CrashBandicoot4.jpg', '2020-10-02', "Crash Bandicoot 4", 29.99, 35, 4, 'Crash Bandicoot 4: It’s About Time para PC es el octavo de la serie de juegos de Crash Bandicoot y es la secuela directa de Crash Bandicoot: N Sane Trilogy, que ocurre después de los eventos de Crash Bandicoot 3: Warped. Únete a Crash, su hermana Coco y un pequeño grupo de amigos decididos en su misión de salvar más que el mundo esta vez.', 'En juegos anteriores de Crash Bandicoot, el villano Dr. Neo Cortex y el Dr. Nefarious Trophy fueron derrotados por Crash con la ayuda del espíritu de un médico brujo que habita una máscara llamada Aku-Aku. En este juego, el gemelo malvado de Aku-Aku, que también habita una máscara y se llama Uka-Uka, ayuda a la pareja malvada a escapar de su encarcelamiento, y entonces el juego comienza.
Pero la pareja de villanos no quiere dominar el mundo en este juego, ni siquiera la dominación universal. No, lo que quieren esta vez es dominar todo el multiverso y eso es un paso demasiado grande no solo para Crash y Coco, sino también para un antiguo enemigo, Dingodile, y para una versión de realidad alternativa de la ex novia de Crash, Tawna. Tawna, en encarnaciones anteriores, era un poco inocente: en este juego, es un personaje con un pasado trágico y tiene sus propias razones para pelear.'),
('WoWDragonflight.jpg', '2022-08-14', 'WoW: Dragonflight', 39.99, 5, 6, 'Los Vuelos de Azeroth han regresado, llamados a defender su ancestral hogar, las Islas Dragón. Rebosante de magia elemental y de las energías vitales de Azeroth, este archipiélago despierta de nuevo. Está en tus manos explorar sus maravillas primordiales y descubrir los olvidados secretos que oculta.', 'Domina el arte de montar dragones, una nueva forma de desplazarte por los cielos. Explora las nuevas zonas y consigue cuatro nuevos dracos de las Islas Dragón, monturas únicas que puedes personalizar a tu gusto. Con millones de combinaciones posibles, jamás verás dos dracos iguales. Utiliza tus nuevas facultades de jinete para mantener a tu draco en el aire. ¡Pero cuidado! Los habitantes de las Islas Dragón no dudarán en derribar a los jinetes más inexpertos. Las Islas Dragón son el hogar ancestral de los Vuelos de Azeroth. Cuando el Gran Cataclismo resquebrajó el mundo, la magia de las islas fue absorbida y el continente quedó sumido en un profundo letargo. Con el despertar de las Islas Dragón, los conflictos y amenazas de antaño despiertan de su largo sueño.'),
("TinyTinasWonderlands.jpg", '2022-03-25', "Tiny Tina's Wonderlands", 59.99, 20, 5, '¡Embárcate en una increíble aventura llena de extravagancias, asombro y armamento de alta potencia! Balas, magia y espadas tendrán cabida en este caótico mundo de fantasía que cobra vida gracias a la impredecible Tina Chiquitina. Crea a tu propio héroe multiclase y saquea, dispara, corta y lanza hechizos para abrirte paso a través de estrafalarios enemigos y mazmorras repletas de botín para detener al tiránico Señor de los Dragones. Aquí todo el mundo es bienvenido, ¡así que únete a la fiesta, ponte unas botas de aventura y saca tu lado caótico genial!', 'La incontrolable Tina Chiquitina te guiará a través de un extraordinario reino con forma de juego de mesa donde las reglas son prácticamente inexistentes. ¡Explora un enorme supramundo lleno de majestuosas ciudades, húmedos bosques de hongos, fortalezas amenazadoras y mucho más! Revienta a los enemigos con poderosas armas y devastadores hechizos en frenéticas batallas en primera persona. Usa tu potencia de fuego para derrotar a legiones de enemigos, como cansinos esqueletos, tiburones terrestres y colosales jefes. Y luego, ¡adéntrate en peligrosas mazmorras para conseguir botín de primera! En la mesa, junto a ti, estarán el testarudo capitán Valentine y Frette, un robot obsesionado con las reglas. Durante tu misión para derrotar al Señor de los Dragones, conocerás a un adorable elenco de inadaptados, como un bárdaro que toca el laúd o tu propia Hada Tollina. Crea al héroe perfecto gracias a las muchas opciones de personalización, como un sistema de multiclases que te permite mezclar y combinar seis árboles de habilidades únicos, todos con sus alucinantes habilidades. Sube de nivel, mejora a tu personaje, amplía tu arsenal y conviértete en el trotamundos definitivo.'),
('GodofWarRagnarok.jpg', '2022-01-01', 'God of War: Ragnarok', 69.99, 10, 4, 'Juntos, Kratos y Atreus se adentran en los nueve reinos en busca de respuestas mientras las fuerzas de Asgard se preparan para la guerra. A lo largo de su aventura, explorarán paisajes mitológicos increíbles, reunirán aliados de los nueve reinos y se enfrentarán a imponentes enemigos con aspecto de monstruos y dioses nórdicos.', 'A medida que se avecina la amenaza del Ragnarök, Kratos y Atreus tendrán que elegir entre la seguridad de su familia y la de los reinos...
Aquellos que desafían al destino
Atreus busca información que lo ayude a entender la profecía de "Loki" y el papel que desempeñará en el Ragnarök. Kratos debe decidir entre someterse al miedo de repetir sus errores o dejar atrás el pasado y convertirse en el padre que Atreus necesita.'),
("RedDeadRedemption2.jpg", '2018-10-26', "Red Dead Redemption 2", 59.99, 50, 4, 'Red Dead Redemption 2 para PC es un juego de acción y aventuras de mundo abierto en el que el jugador puede vagar libremente. Cuenta algunos elementos en tercera persona, además de otras modalidades de juego en primera persona. El jugador puede cometer crímenes, pero de hacerlo deberá estar preparado para ser perseguido por las fuerzas del orden, ¡quienes estarán dispuestas a hacer valer todo el peso de la ley sobre los delincuentes!', 'RDR2, como se conoce afectuosamente al juego, fue lanzado para otras plataformas antes de ser publicado para PC, y durante el período de su lanzamiento original llegó a posicionarse como uno de los títulos más vendidos de todos los tiempos, incluso antes que se incluyeran las cifras de venta en su versión para PC.
La razón de la popularidad del juego no es difícil de entender. A diferencia de otros juegos en los que el caos y la destrucción son la clave, este juego te permite sumergirte en la belleza de los paisajes del Salvaje Oeste, y formar lazos de empatía y afecto con otros jugadores y con PNJs (personajes no jugables) en los momentos de calma que se te presenten entra una secuencia de acción y otra ¡de las cuales hallarás de sobra!'),
('HollowKnight.jpg', '2017-02-24', 'Hollow Knight', 18.99, 30, 2, 'Hollow Knight es una aventura de acción clásica en 2D ambientada en un vasto mundo interconectado. Explora cavernas tortuosas, ciudades antiguas y páramos mortales. Combate contra criaturas corrompidas, haz amistad con extraños insectos y resuelve los antiguos misterios que yacen en el corazón de reino.', 'El mundo de Hollow Knight cobra vida gracias a sus detalles vívidos y melancólicos, sus cavernas con criaturas extrañas y terroríficas, y su animación a mano con un estilo tradicional en 2D.
Cada nueva zona que descubras es única, hermosa y extraña, con cantidad de criaturas y personajes nuevos. Disfruta de las vistas y descubre nuevas maravillas ocultas fuera de los caminos habituales.
Si te gusta la jugabilidad clásica, los personajes adorables a la vez que extraños, las aventuras épicas y los mundos bellos y de estilo gótico, ¡entonces Hollow Knight te espera!');


insert into usuarios (avatar, nombre, apellidos, nick, password, tlf, email, privado, status, fecharegistro, idrole) values 
('avatarNitram.png' ,'Martin','Laviada','Nitram','$2a$12$7WkthpqyKxJy52k0eBfrlORys/9rSGZ86CQu0ib7fr9dsDe2I7V62', '658585858','martinlb18@educastur.es', false,true,'2020-12-12',1),
('avatarVaroSensei.jpg', 'Alvaro', 'Jimenez', 'VaroSensei', '$2a$12$7WkthpqyKxJy52k0eBfrlORys/9rSGZ86CQu0ib7fr9dsDe2I7V62', '789454545', 'alvaro@educastur.es', false, true, '2020-12-12', 2),
('avatarBenav.jpg', 'Victor', 'Benavides', 'Benav', '$2a$12$7WkthpqyKxJy52k0eBfrlORys/9rSGZ86CQu0ib7fr9dsDe2I7V62', '785454545', 'victos@educastur.es', false, true, '2020-12-12', 2),
('avatarNierra.jpg' ,'Xènia', 'Garcia', 'Nierra', '$2a$12$7WkthpqyKxJy52k0eBfrlORys/9rSGZ86CQu0ib7fr9dsDe2I7V62', '698585858', 'xenia@educastur.es', false, true, '2020-12-12', 1);

insert into ejemplares (clave, fechainserc, idproducto) values ('kdjjYBQuis', '2020-12-12', 1);
insert into ejemplares (clave, fechainserc, idproducto) values ('8vVEqDh8tQ', '2020-12-12', 1);
insert into ejemplares (clave, fechainserc, idproducto) values ('PE8dd6YMjE', '2020-12-12', 1);
insert into ejemplares (clave, fechainserc, idproducto) values ('oC5PK3qd1x', '2020-12-12', 2);
insert into ejemplares (clave, fechainserc, idproducto) values ('v1Iv8nubtX', '2020-12-12', 3);

insert into pedidos (fechacompra, estado, idusuario) values ('2000-12-12', 'Pendiente', 1);